---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whisper
  namespace: home-cloud
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: rhasspy/wyoming-whisper
              tag: latest
              pullPolicy: Always
            env:
              TZ: ${TIMEZONE}
            args:
              - --model
                # tiny-int8 (43 MB)
                # tiny (152 MB)
                # base-int8 (80 MB)
                # base (291 MB)
                # small-int8 (255 MB)
                # small (968 MB)
                # medium-int8 (786 MB)
                # medium (3.1 GB)
              - small
              - --language
              - it
        strategy: Recreate
    service:
      main:
        ports:
          http:
            enabled: false
          tcp:
            port: 10300
            protocol: TCP
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /data
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
