---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 10m0s
